server:
  servlet:
    context-path: /template
spring:
  profiles:
    active: dev
    include: basic
    group:
      dev: basic-dev,core-dev
      prod: basic-prod,core-prod
appConfig:
  moduleType: admin
  excludePaths: /admin_sys_user/login,/admin_sys_user/qrLogin,/login/getLoginVerifyImg
