server:
  servlet:
    context-path: /lists
spring:
  profiles:
    include:
      - basic
      - dev
      - basic-dev
appConfig:
  moduleType: admin
  excludePaths: /admin_sys_user/login,/admin_sys_user/qrLogin,/login/getLoginVerifyImg
